name: Create uf2 release for new version tag

on: [push]

# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  compile-uf2:
    runs-on: ubuntu-latest

    steps:
      - name: clone EuroPi
        uses: actions/checkout@v3
        with:
          path: europi

      - name: clone micropython
        uses: actions/checkout@v3
        with:
          repository: micropython/micropython
          ref: v1.19.1
          path: micropython
      
      - name: install os deps
        run: sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: prepare micropython build
        working-directory: micropython
        run: make -C ports/rp2 submodules && make -C mpy-cross

      - name: copy europi into micropython modules
        run: |
          mkdir micropython/ports/rp2/modules/contrib
          mkdir micropython/ports/rp2/modules/experimental
          cp -r europi/software/firmware/*.py micropython/ports/rp2/modules
          cp -r europi/software/firmware/experimental micropython/ports/rp2/modules/experimental
          cp -r europi/software/contrib/*.py micropython/ports/rp2/modules/contrib
        
      - run: wget https://raw.githubusercontent.com/stlehmann/micropython-ssd1306/master/ssd1306.py -O micropython/ports/rp2/modules/ssd1306.py
      - run: sed -i 's/progsize=256)/progsize=1024)/g' micropython/ports/rp2/modules/_boot.py
      - run: |
          cat <<EOF >> micropython/ports/rp2/modules/main.py
          import gc
          gc.collect()
          from contrib.menu import *
          BootloaderMenu(EUROPI_SCRIPT_CLASSES).main()
          EOF

      - run: tree micropython/ports/rp2/modules
      - run: cat micropython/ports/rp2/modules/main.py

      - name: compile micropython and firmware modules
        working-directory: micropython/ports/rp2
        run: make

      - name: release asset version
        id: release-asset-version
        run: |
          VERSION=`grep -oP '(?<=")[\d\.]+(?=")' micropython/ports/rp2/modules/version.py`
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      
      - run: cp micropython/ports/rp2/build-PICO/firmware.uf2 europi-v${{ steps.release-asset-version.outputs.VERSION }}.uf2

      - name: create github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          draft: true
          files: europi-v${{ steps.release-asset-version.outputs.VERSION }}.uf2
